stages:
    - build
    - test
    
.artifacts_test_executables: &artifacts_test_executables
    artifacts:
        paths:
            - tests/unittest
        expire_in: 5 minutes

building:
    stage: build
    script:
        - make clean
        - make all
        - make tests
    <<: *artifacts_test_executables

testing/unittest:
    stage: test
    script:
        - tests/unittest -v
