stages:
    - build
    - test
    - coverage
    
.building_artifacts: &building_artifacts
    artifacts:
        paths:
            - .o/
            - .d/
            - libj1939.a
            - tests/
        expire_in: 5 minutes
        
.coverage_artifacts: &coverage_artifacts
    artifacts:
        paths:
            - coverage_report

building:
    stage: build
    script:
        - make clean
        - make all
        - make tests
    <<: *building_artifacts

testing/unittest:
    stage: test
    script:
        - make check
    <<: *building_artifacts

generate/coverage:
    stage: coverage
    script:
        - make coverage
    <<: *coverage_artifacts
    dependencies:
        - testing/unittest
