stages:
    - build
    - test
    - coverage
    
.building_artifacts: &building_artifacts
    artifacts:
        paths:
            - .o/
            - libj1939.a
            - tests/unittest
        expire_in: 5 minutes

.testing_artifacts: &testing_artifacts
    artifacts:
        paths:
            - .o/**/*.gcda
            - .o/**/*.gcno
        expire_in: 5 minutes
        
.coverage_artifacts: &coverage_artifacts
    artifacts:
        paths:
            - coverage_report

building:
    stage: build
    script:
        - make clean
        - make COVERAGE=1 all
        - make tests
    <<: *building_artifacts

testing/unittest:
    stage: test
    script:
        - make check
    <<: *testing_artifacts

generate/coverage:
    stage: coverage
    script:
        - make coverage
    coverage: '/^\s*lines......: (\d+.\d+\%)/'
    <<: *coverage_artifacts
    dependencies:
        - testing/unittest
