stages:
    - build
    - test
    - coverage

.base:
    image: gcc:10-bullseye
    tags:
        - "docker"
    
.building_artifacts: &building_artifacts
    extends: .base
    artifacts:
        paths:
            - .o/
            - libj1939.a
            - tests/unittest
        expire_in: 5 minutes

.testing_artifacts: &testing_artifacts
    extends: .base
    artifacts:
        paths:
            - .o/
        expire_in: 5 minutes
        
.coverage_artifacts: &coverage_artifacts
    extends: .base
    artifacts:
        paths:
            - coverage_report

building:
    stage: build
    script:
        - make distclean
        - make default_defconfig
        - make COVERAGE=1 all
        - make tests
    <<: *building_artifacts

testing/unittest:
    stage: test
    script:
        - make check
    <<: *testing_artifacts

generate/coverage:
    stage: coverage
    before_script:
        - apt update && apt install -y lcov
    script:
        - make coverage
    coverage: '/^\s*lines......: (\d+.\d+\%)/'
    <<: *coverage_artifacts
    dependencies:
        - testing/unittest
