stages:
    - build
    - test
    
.test_executables: &test_executables
    - paths:
        - tests/unittest
    - expire_in: 1 minute

building:
    stage: build
    script:
        - make clean
        - make all
        - make tests
    artifacts: &test_executables

testing/unittest:
    stage: test
    script:
        - tests/unittest -v
